services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"   # acced√©s en http://localhost:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_PORT=5173
      - VITE_HOST=0.0.0.0
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./app:/app:cached
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules:
